### ISSUE TITLE
props.children raise error for unpair tags

### ISSUE THREAD

**Issue by martinsvoboda** [jhukdev/preactement#8]
Hi James, first of all thank you for very interesting library!

I figure our we found bug in when combine unpaired tags in component (`<br>`, `<hr>`, `<img>`...) and props.children. This combination raise "error on line 7 at column 15: Opening and ending tag mismatch: br line 5 and div". Is there any way how to fix this?

![Screenshot 2022-01-12 at 9 06 25](https://user-images.githubusercontent.com/558139/149087990-eb8d2b75-0191-48e5-a248-52cb61679a66.png)

index.js
```
import { define } from 'preactement';

class MyComponent extends Component {
    render(props, state) {
        return <div>
            {props.children}
        </div>
    }
}

define('x-mycomponent', () => MyComponent, { attributes: ['name'] });
```

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Parcel Webcomponent test 2</h1>

    <x-mycomponent name="value">
        <div>
            Lorem ipsum
            <br>
            Lorem ipsum
        </div>
    </x-mycomponent>

    <script type="module" src="./index.js"></script>
</body>
</html>
```

**Comment by jhukdev** [comment]
@martinsvoboda Ok ready to go!

https://github.com/jhukdev/preactement/releases/tag/1.6.5

**Comment by martinsvoboda** [comment]
Works like a charm! Thanks for super-fast support!
